SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[Stephanie]'
GO
ALTER TABLE [dbo].[Stephanie] DROP CONSTRAINT [PK__Stephani__3214EC2715EFA871]
GO
PRINT N'Dropping [dbo].[Stephanie]'
GO
DROP TABLE [dbo].[Stephanie]
GO

