SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[Stephanie2]'
GO
ALTER TABLE [dbo].[Stephanie2] DROP CONSTRAINT [PK__Stephani__3214EC2706FC2664]
GO
PRINT N'Dropping [dbo].[Stephanie2]'
GO
DROP TABLE [dbo].[Stephanie2]
GO

