SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[Stephanie]'
GO
CREATE TABLE [dbo].[Stephanie]
(
[ID] [int] NOT NULL
)
GO
PRINT N'Creating primary key [PK__Stephani__3214EC2715EFA871] on [dbo].[Stephanie]'
GO
ALTER TABLE [dbo].[Stephanie] ADD CONSTRAINT [PK__Stephani__3214EC2715EFA871] PRIMARY KEY CLUSTERED ([ID])
GO

