SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[Stephanie2]'
GO
CREATE TABLE [dbo].[Stephanie2]
(
[ID] [int] NOT NULL
)
GO
PRINT N'Creating primary key [PK__Stephani__3214EC2706FC2664] on [dbo].[Stephanie2]'
GO
ALTER TABLE [dbo].[Stephanie2] ADD CONSTRAINT [PK__Stephani__3214EC2706FC2664] PRIMARY KEY CLUSTERED ([ID])
GO

